export default [
    { path: '/settings/system', component: () => import('@/pages/settings/settings/SystemSettings.vue') },
    { path: '/settings/cron', component: () => import('@/pages/settings/settings/Cron.vue') },
    { path: '/settings/license-type', component: () => import('@/pages/settings/settings/licenseType/Index.vue') },
    { path: '/settings/license-type/:id/edit', component: () => import('@/pages/settings/settings/licenseType/Edit.vue') },
    { path: '/settings/license-permissions', component: () => import('@/pages/settings/settings/LicensePermissions.vue') },
    { path: '/settings/file-storage', component: () => import('@/pages/settings/settings/FileStorage.vue') },
    { path: '/settings/payment-gateway', component: () => import('@/pages/settings/settings/paymentGateway/Index.vue') },
    { path: '/settings/payment-gateway/:id/edit', component: () => import('@/pages/settings/settings/paymentGateway/Edit.vue') },
    { path: '/settings/system-managers', component: () => import('@/pages/settings/settings/SystemManagers.vue') },
    { path: '/settings/third-party-apps', component: () => import('@/pages/settings/settings/thirdPartyApps/Index.vue') },
    { path: '/settings/cloud-details', component: () => import('@/pages/settings/settings/CloudDetails.vue') },
    { path: '/settings/localized-license', component: () => import('@/pages/settings/settings/LocalizedLicense.vue') },
    { path: '/settings/debugging', component: () => import('@/pages/settings/settings/DebuggingSettings.vue') },
    { path: '/settings/social-logins', component: () => import('@/pages/settings/settings/socialLogins/Index.vue') },
    { path: '/settings/social-logins/:id/edit', component: () => import('@/pages/settings/settings/socialLogins/Edit.vue') },
    { path: '/settings/language', component: () => import('@/pages/settings/settings/Language.vue') },
    { path: '/settings/whatsapp-users', component: () => import('@/pages/settings/settings/WhatsappUsers.vue') },
    { path: '/settings/contact-options', component: () => import('@/pages/settings/settings/ContactOptions.vue') },
]
