<?php

return [
    [
        'id' => '1',
        'code' => 'AAD',
        'symbol' => '$',
        'name' => 'Antarctican dollar',
    ],
    [
        'id' => '2',
        'code' => 'AED',
        'symbol' => 'إ.د',
        'name' => 'United Arab Emirates dirham',
    ],
    [
        'id' => '3',
        'code' => 'AFN',
        'symbol' => '؋',
        'name' => 'Afghan afghani',
    ],
    [
        'id' => '4',
        'code' => 'ALL',
        'symbol' => 'Lek',
        'name' => 'Albanian lek',
    ],
    [
        'id' => '5',
        'code' => 'AMD',
        'symbol' => '֏',
        'name' => 'Armenian dram',
    ],
    [
        'id' => '6',
        'code' => 'ANG',
        'symbol' => 'ƒ',
        'name' => 'Netherlands Antillean guilder',
    ],
    [
        'id' => '7',
        'code' => 'AOA',
        'symbol' => 'Kz',
        'name' => 'Angolan kwanza',
    ],
    [
        'id' => '8',
        'code' => 'ARS',
        'symbol' => '$',
        'name' => 'Argentine peso',
    ],
    [
        'id' => '9',
        'code' => 'AUD',
        'symbol' => '$',
        'name' => 'Australian dollar',
    ],
    [
        'id' => '10',
        'code' => 'AWG',
        'symbol' => 'ƒ',
        'name' => 'Aruban florin',
    ],
    [
        'id' => '11',
        'code' => 'AZN',
        'symbol' => 'm',
        'name' => 'Azerbaijani manat',
    ],
    [
        'id' => '12',
        'code' => 'BAM',
        'symbol' => 'KM',
        'name' => 'Bosnia and Herzegovina convertible mark',
    ],
    [
        'id' => '13',
        'code' => 'BBD',
        'symbol' => 'Bds$',
        'name' => 'Barbadian dollar',
    ],
    [
        'id' => '14',
        'code' => 'BDT',
        'symbol' => '৳',
        'name' => 'Bangladeshi taka',
    ],
    [
        'id' => '15',
        'code' => 'BGN',
        'symbol' => 'Лв.',
        'name' => 'Bulgarian lev',
    ],
    [
        'id' => '16',
        'code' => 'BHD',
        'symbol' => '.د.ب',
        'name' => 'Bahraini dinar',
    ],
    [
        'id' => '17',
        'code' => 'BIF',
        'symbol' => 'FBu',
        'name' => 'Burundian franc',
    ],
    [
        'id' => '18',
        'code' => 'BMD',
        'symbol' => '$',
        'name' => 'Bermudian dollar',
    ],
    [
        'id' => '19',
        'code' => 'BND',
        'symbol' => 'B$',
        'name' => 'Brunei dollar',
    ],
    [
        'id' => '20',
        'code' => 'BOB',
        'symbol' => 'Bs.',
        'name' => 'Bolivian boliviano',
    ],
    [
        'id' => '21',
        'code' => 'BRL',
        'symbol' => 'R$',
        'name' => 'Brazilian real',
    ],
    [
        'id' => '22',
        'code' => 'BSD',
        'symbol' => 'B$',
        'name' => 'Bahamian dollar',
    ],
    [
        'id' => '23',
        'code' => 'BTN',
        'symbol' => 'Nu.',
        'name' => 'Bhutanese ngultrum',
    ],
    [
        'id' => '24',
        'code' => 'BWP',
        'symbol' => 'P',
        'name' => 'Botswana pula',
    ],
    [
        'id' => '25',
        'code' => 'BYN',
        'symbol' => 'Br',
        'name' => 'Belarusian ruble',
    ],
    [
        'id' => '26',
        'code' => 'BZD',
        'symbol' => '$',
        'name' => 'Belize dollar',
    ],
    [
        'id' => '27',
        'code' => 'CAD',
        'symbol' => '$',
        'name' => 'Canadian dollar',
    ],
    [
        'id' => '28',
        'code' => 'CDF',
        'symbol' => 'FC',
        'name' => 'Congolese Franc',
    ],
    [
        'id' => '29',
        'code' => 'CHF',
        'symbol' => 'CHf',
        'name' => 'Swiss franc',
    ],
    [
        'id' => '30',
        'code' => 'CLP',
        'symbol' => '$',
        'name' => 'Chilean peso',
    ],
    [
        'id' => '31',
        'code' => 'CNY',
        'symbol' => '¥',
        'name' => 'Chinese yuan',
    ],
    [
        'id' => '32',
        'code' => 'COP',
        'symbol' => '$',
        'name' => 'Colombian peso',
    ],
    [
        'id' => '33',
        'code' => 'CRC',
        'symbol' => '₡',
        'name' => 'Costa Rican colón',
    ],
    [
        'id' => '34',
        'code' => 'CUP',
        'symbol' => '$',
        'name' => 'Cuban peso',
    ],
    [
        'id' => '35',
        'code' => 'CVE',
        'symbol' => '$',
        'name' => 'Cape Verdean escudo',
    ],
    [
        'id' => '36',
        'code' => 'CZK',
        'symbol' => 'Kč',
        'name' => 'Czech koruna',
    ],
    [
        'id' => '37',
        'code' => 'DJF',
        'symbol' => 'Fdj',
        'name' => 'Djiboutian franc',
    ],
    [
        'id' => '38',
        'code' => 'DKK',
        'symbol' => 'Kr.',
        'name' => 'Danish krone',
    ],
    [
        'id' => '39',
        'code' => 'DOP',
        'symbol' => '$',
        'name' => 'Dominican peso',
    ],
    [
        'id' => '40',
        'code' => 'DZD',
        'symbol' => 'دج',
        'name' => 'Algerian dinar',
    ],
    [
        'id' => '41',
        'code' => 'EGP',
        'symbol' => 'ج.م',
        'name' => 'Egyptian pound',
    ],
    [
        'id' => '42',
        'code' => 'ERN',
        'symbol' => 'Nfk',
        'name' => 'Eritrean nakfa',
    ],
    [
        'id' => '43',
        'code' => 'ETB',
        'symbol' => 'Nkf',
        'name' => 'Ethiopian birr',
    ],
    [
        'id' => '44',
        'code' => 'EUR',
        'symbol' => '€',
        'name' => 'Euro',
    ],
    [
        'id' => '45',
        'code' => 'FJD',
        'symbol' => 'FJ$',
        'name' => 'Fijian dollar',
    ],
    [
        'id' => '46',
        'code' => 'FKP',
        'symbol' => '£',
        'name' => 'Falkland Islands pound',
    ],
    [
        'id' => '47',
        'code' => 'GBP',
        'symbol' => '£',
        'name' => 'British pound',
    ],
    [
        'id' => '48',
        'code' => 'GEL',
        'symbol' => 'ლ',
        'name' => 'Georgian lari',
    ],
    [
        'id' => '49',
        'code' => 'GHS',
        'symbol' => 'GH₵',
        'name' => 'Ghanaian cedi',
    ],
    [
        'id' => '50',
        'code' => 'GIP',
        'symbol' => '£',
        'name' => 'Gibraltar pound',
    ],
    [
        'id' => '51',
        'code' => 'GMD',
        'symbol' => 'D',
        'name' => 'Gambian dalasi',
    ],
    [
        'id' => '52',
        'code' => 'GNF',
        'symbol' => 'FG',
        'name' => 'Guinean franc',
    ],
    [
        'id' => '53',
        'code' => 'GTQ',
        'symbol' => 'Q',
        'name' => 'Guatemalan quetzal',
    ],
    [
        'id' => '54',
        'code' => 'GYD',
        'symbol' => '$',
        'name' => 'Guyanese dollar',
    ],
    [
        'id' => '55',
        'code' => 'HKD',
        'symbol' => '$',
        'name' => 'Hong Kong dollar',
    ],
    [
        'id' => '56',
        'code' => 'HNL',
        'symbol' => 'L',
        'name' => 'Honduran lempira',
    ],
    [
        'id' => '57',
        'code' => 'HTG',
        'symbol' => 'G',
        'name' => 'Haitian gourde',
    ],
    [
        'id' => '58',
        'code' => 'HUF',
        'symbol' => 'Ft',
        'name' => 'Hungarian forint',
    ],
    [
        'id' => '59',
        'code' => 'IDR',
        'symbol' => 'Rp',
        'name' => 'Indonesian rupiah',
    ],
    [
        'id' => '60',
        'code' => 'ILS',
        'symbol' => '₪',
        'name' => 'Israeli new shekel',
    ],
    [
        'id' => '61',
        'code' => 'INR',
        'symbol' => '₹',
        'name' => 'Indian rupee',
    ],
    [
        'id' => '62',
        'code' => 'IQD',
        'symbol' => 'د.ع',
        'name' => 'Iraqi dinar',
    ],
    [
        'id' => '63',
        'code' => 'IRR',
        'symbol' => '﷼',
        'name' => 'Iranian rial',
    ],
    [
        'id' => '64',
        'code' => 'ISK',
        'symbol' => 'ko',
        'name' => 'Icelandic króna',
    ],
    [
        'id' => '65',
        'code' => 'JMD',
        'symbol' => 'J$',
        'name' => 'Jamaican dollar',
    ],
    [
        'id' => '66',
        'code' => 'JOD',
        'symbol' => 'ا.د',
        'name' => 'Jordanian dinar',
    ],
    [
        'id' => '67',
        'code' => 'JPY',
        'symbol' => '¥',
        'name' => 'Japanese yen',
    ],
    [
        'id' => '68',
        'code' => 'KES',
        'symbol' => 'KSh',
        'name' => 'Kenyan shilling',
    ],
    [
        'id' => '69',
        'code' => 'KGS',
        'symbol' => 'лв',
        'name' => 'Kyrgyzstani som',
    ],
    [
        'id' => '70',
        'code' => 'KHR',
        'symbol' => 'KHR',
        'name' => 'Cambodian riel',
    ],
    [
        'id' => '71',
        'code' => 'KMF',
        'symbol' => 'CF',
        'name' => 'Comorian franc',
    ],
    [
        'id' => '72',
        'code' => 'KPW',
        'symbol' => '₩',
        'name' => 'North Korean Won',
    ],
    [
        'id' => '73',
        'code' => 'KRW',
        'symbol' => '₩',
        'name' => 'Won',
    ],
    [
        'id' => '74',
        'code' => 'KWD',
        'symbol' => 'ك.د',
        'name' => 'Kuwaiti dinar',
    ],
    [
        'id' => '75',
        'code' => 'KYD',
        'symbol' => '$',
        'name' => 'Cayman Islands dollar',
    ],
    [
        'id' => '76',
        'code' => 'KZT',
        'symbol' => 'лв',
        'name' => 'Kazakhstani tenge',
    ],
    [
        'id' => '77',
        'code' => 'LAK',
        'symbol' => '₭',
        'name' => 'Lao kip',
    ],
    [
        'id' => '78',
        'code' => 'LBP',
        'symbol' => '£',
        'name' => 'Lebanese pound',
    ],
    [
        'id' => '79',
        'code' => 'LKR',
        'symbol' => 'Rs',
        'name' => 'Sri Lankan rupee',
    ],
    [
        'id' => '80',
        'code' => 'LRD',
        'symbol' => '$',
        'name' => 'Liberian dollar',
    ],
    [
        'id' => '81',
        'code' => 'LSL',
        'symbol' => 'L',
        'name' => 'Lesotho loti',
    ],
    [
        'id' => '82',
        'code' => 'LYD',
        'symbol' => 'د.ل',
        'name' => 'Libyan dinar',
    ],
    [
        'id' => '83',
        'code' => 'MAD',
        'symbol' => 'DH',
        'name' => 'Moroccan dirham',
    ],
    [
        'id' => '84',
        'code' => 'MDL',
        'symbol' => 'L',
        'name' => 'Moldovan leu',
    ],
    [
        'id' => '85',
        'code' => 'MGA',
        'symbol' => 'Ar',
        'name' => 'Malagasy ariary',
    ],
    [
        'id' => '86',
        'code' => 'MKD',
        'symbol' => 'ден',
        'name' => 'Denar',
    ],
    [
        'id' => '87',
        'code' => 'MMK',
        'symbol' => 'K',
        'name' => 'Burmese kyat',
    ],
    [
        'id' => '88',
        'code' => 'MNT',
        'symbol' => '₮',
        'name' => 'Mongolian tögrög',
    ],
    [
        'id' => '89',
        'code' => 'MOP',
        'symbol' => '$',
        'name' => 'Macanese pataca',
    ],
    [
        'id' => '90',
        'code' => 'MRU',
        'symbol' => 'UM',
        'name' => 'Mauritanian ouguiya',
    ],
    [
        'id' => '91',
        'code' => 'MUR',
        'symbol' => '₨',
        'name' => 'Mauritian rupee',
    ],
    [
        'id' => '92',
        'code' => 'MVR',
        'symbol' => 'Rf',
        'name' => 'Maldivian rufiyaa',
    ],
    [
        'id' => '93',
        'code' => 'MWK',
        'symbol' => 'MK',
        'name' => 'Malawian kwacha',
    ],
    [
        'id' => '94',
        'code' => 'MXN',
        'symbol' => '$',
        'name' => 'Mexican peso',
    ],
    [
        'id' => '95',
        'code' => 'MYR',
        'symbol' => 'RM',
        'name' => 'Malaysian ringgit',
    ],
    [
        'id' => '96',
        'code' => 'MZN',
        'symbol' => 'MT',
        'name' => 'Mozambican metical',
    ],
    [
        'id' => '97',
        'code' => 'NAD',
        'symbol' => '$',
        'name' => 'Namibian dollar',
    ],
    [
        'id' => '98',
        'code' => 'NGN',
        'symbol' => '₦',
        'name' => 'Nigerian naira',
    ],
    [
        'id' => '99',
        'code' => 'NIO',
        'symbol' => 'C$',
        'name' => 'Nicaraguan córdoba',
    ],
    [
        'id' => '100',
        'code' => 'NOK',
        'symbol' => 'ko',
        'name' => 'Norwegian krone',
    ],
    [
        'id' => '101',
        'code' => 'NPR',
        'symbol' => '₨',
        'name' => 'Nepalese rupee',
    ],
    [
        'id' => '102',
        'code' => 'NZD',
        'symbol' => '$',
        'name' => 'New Zealand dollar',
    ],
    [
        'id' => '103',
        'code' => 'OMR',
        'symbol' => '.ع.ر',
        'name' => 'Omani rial',
    ],
    [
        'id' => '104',
        'code' => 'PAB',
        'symbol' => 'B/.',
        'name' => 'Panamanian balboa',
    ],
    [
        'id' => '105',
        'code' => 'PEN',
        'symbol' => 'S/.',
        'name' => 'Peruvian sol',
    ],
    [
        'id' => '106',
        'code' => 'PGK',
        'symbol' => 'K',
        'name' => 'Papua New Guinean kina',
    ],
    [
        'id' => '107',
        'code' => 'PHP',
        'symbol' => '₱',
        'name' => 'Philippine peso',
    ],
    [
        'id' => '108',
        'code' => 'PKR',
        'symbol' => '₨',
        'name' => 'Pakistani rupee',
    ],
    [
        'id' => '109',
        'code' => 'PLN',
        'symbol' => 'zł',
        'name' => 'Polish złoty',
    ],
    [
        'id' => '110',
        'code' => 'PYG',
        'symbol' => '₲',
        'name' => 'Paraguayan guarani',
    ],
    [
        'id' => '111',
        'code' => 'QAR',
        'symbol' => 'ق.ر',
        'name' => 'Qatari riyal',
    ],
    [
        'id' => '112',
        'code' => 'RON',
        'symbol' => 'lei',
        'name' => 'Romanian leu',
    ],
    [
        'id' => '113',
        'code' => 'RSD',
        'symbol' => 'din',
        'name' => 'Serbian dinar',
    ],
    [
        'id' => '114',
        'code' => 'RUB',
        'symbol' => '₽',
        'name' => 'Russian ruble',
    ],
    [
        'id' => '115',
        'code' => 'RWF',
        'symbol' => 'FRw',
        'name' => 'Rwandan franc',
    ],
    [
        'id' => '116',
        'code' => 'SAR',
        'symbol' => '﷼',
        'name' => 'Saudi riyal',
    ],
    [
        'id' => '117',
        'code' => 'SBD',
        'symbol' => 'Si$',
        'name' => 'Solomon Islands dollar',
    ],
    [
        'id' => '118',
        'code' => 'SCR',
        'symbol' => 'SRe',
        'name' => 'Seychellois rupee',
    ],
    [
        'id' => '119',
        'code' => 'SDG',
        'symbol' => '.س.ج',
        'name' => 'Sudanese pound',
    ],
    [
        'id' => '120',
        'code' => 'SEK',
        'symbol' => 'ko',
        'name' => 'Swedish krona',
    ],
    [
        'id' => '121',
        'code' => 'SGD',
        'symbol' => '$',
        'name' => 'Singapore dollar',
    ],
    [
        'id' => '122',
        'code' => 'SHP',
        'symbol' => '£',
        'name' => 'Saint Helena pound',
    ],
    [
        'id' => '123',
        'code' => 'SLL',
        'symbol' => 'Le',
        'name' => 'Sierra Leonean leone',
    ],
    [
        'id' => '124',
        'code' => 'SOS',
        'symbol' => 'Sh.so.',
        'name' => 'Somali shilling',
    ],
    [
        'id' => '125',
        'code' => 'SRD',
        'symbol' => '$',
        'name' => 'Surinamese dollar',
    ],
    [
        'id' => '126',
        'code' => 'SSP',
        'symbol' => '£',
        'name' => 'South Sudanese pound',
    ],
    [
        'id' => '127',
        'code' => 'STN',
        'symbol' => 'Db',
        'name' => 'Dobra',
    ],
    [
        'id' => '128',
        'code' => 'SYP',
        'symbol' => 'LS',
        'name' => 'Syrian pound',
    ],
    [
        'id' => '129',
        'code' => 'SZL',
        'symbol' => 'E',
        'name' => 'Lilangeni',
    ],
    [
        'id' => '130',
        'code' => 'THB',
        'symbol' => '฿',
        'name' => 'Thai baht',
    ],
    [
        'id' => '131',
        'code' => 'TJS',
        'symbol' => 'SM',
        'name' => 'Tajikistani somoni',
    ],
    [
        'id' => '132',
        'code' => 'TMT',
        'symbol' => 'T',
        'name' => 'Turkmenistan manat',
    ],
    [
        'id' => '133',
        'code' => 'TND',
        'symbol' => 'ت.د',
        'name' => 'Tunisian dinar',
    ],
    [
        'id' => '134',
        'code' => 'TOP',
        'symbol' => '$',
        'name' => 'Tongan paʻanga',
    ],
    [
        'id' => '135',
        'code' => 'TRY',
        'symbol' => '₺',
        'name' => 'Turkish lira',
    ],
    [
        'id' => '136',
        'code' => 'TTD',
        'symbol' => '$',
        'name' => 'Trinidad and Tobago dollar',
    ],
    [
        'id' => '137',
        'code' => 'TWD',
        'symbol' => '$',
        'name' => 'New Taiwan dollar',
    ],
    [
        'id' => '138',
        'code' => 'TZS',
        'symbol' => 'TSh',
        'name' => 'Tanzanian shilling',
    ],
    [
        'id' => '139',
        'code' => 'UAH',
        'symbol' => '₴',
        'name' => 'Ukrainian hryvnia',
    ],
    [
        'id' => '140',
        'code' => 'UGX',
        'symbol' => 'USh',
        'name' => 'Ugandan shilling',
    ],
    [
        'id' => '141',
        'code' => 'USD',
        'symbol' => '$',
        'name' => 'United States dollar',
    ],
    [
        'id' => '142',
        'code' => 'UYU',
        'symbol' => '$',
        'name' => 'Uruguayan peso',
    ],
    [
        'id' => '143',
        'code' => 'UZS',
        'symbol' => 'лв',
        'name' => 'Uzbekistani soʻm',
    ],
    [
        'id' => '144',
        'code' => 'VES',
        'symbol' => 'Bs',
        'name' => 'Bolívar',
    ],
    [
        'id' => '145',
        'code' => 'VND',
        'symbol' => '₫',
        'name' => 'Vietnamese đồng',
    ],
    [
        'id' => '146',
        'code' => 'VUV',
        'symbol' => 'VT',
        'name' => 'Vanuatu vatu',
    ],
    [
        'id' => '147',
        'code' => 'WST',
        'symbol' => 'SAT',
        'name' => 'Samoan tālā',
    ],
    [
        'id' => '148',
        'code' => 'XAF',
        'symbol' => 'FCFA',
        'name' => 'Central African CFA franc',
    ],
    [
        'id' => '149',
        'code' => 'XCD',
        'symbol' => '$',
        'name' => 'Eastern Caribbean dollar',
    ],
    [
        'id' => '150',
        'code' => 'XOF',
        'symbol' => 'CFA',
        'name' => 'West African CFA franc',
    ],
    [
        'id' => '151',
        'code' => 'XPF',
        'symbol' => '₣',
        'name' => 'CFP franc',
    ],
    [
        'id' => '152',
        'code' => 'YER',
        'symbol' => '﷼',
        'name' => 'Yemeni rial',
    ],
    [
        'id' => '153',
        'code' => 'ZAR',
        'symbol' => 'R',
        'name' => 'South African rand',
    ],
    [
        'id' => '154',
        'code' => 'ZMW',
        'symbol' => 'ZK',
        'name' => 'Zambian kwacha',
    ],
    [
        'id' => '155',
        'code' => 'ZWL',
        'symbol' => '$',
        'name' => 'Zimbabwe Dollar',
    ],
];
