<?php
/**
 * Checks that lines added in this PR (vs development) are covered by tests.
 *
 * Parses git diff to identify new executable lines, then cross-references with
 * the clover.xml generated by PHPUnit to determine which of those lines were hit.
 *
 * Usage: php scripts/check-new-line-coverage.php [workspace] [threshold]
 *
 *   workspace  — absolute path to repo root (default: cwd)
 *   threshold  — minimum % of new executable lines that must be covered (default: 80)
 *
 * stdout : JSON result (for Jenkins to parse and format into a PR comment)
 * stderr : human-readable progress (appears in the Jenkins console log)
 *
 * Exit codes:
 *   0 — passed (or skipped — nothing to check)
 *   1 — coverage below threshold
 */

$workspace  = rtrim($argv[1] ?? getcwd(), '/');
$threshold  = isset($argv[2]) ? (int) $argv[2] : 80;
$cloverFile = "{$workspace}/storage/sonarqube/clover.xml";

if (!file_exists($cloverFile)) {
    fwrite(STDERR, "[SKIP] No clover.xml at {$cloverFile}\n");
    echo json_encode(['skipped' => true, 'reason' => 'no clover.xml']);
    exit(0);
}

// ── Step 1: get added lines per PHP file (reuse shared diff parser) ───────────

$allChangedLines = json_decode(
    shell_exec('php ' . escapeshellarg($workspace . '/scripts/get-changed-lines.php') . ' ' . escapeshellarg($workspace)),
    true
) ?? [];

// Coverage only checks PHP source files (get-changed-lines.php already excluded tests/)
$addedLines = array_filter($allChangedLines, static fn(string $k) => str_ends_with($k, '.php'), ARRAY_FILTER_USE_KEY);

if (empty($addedLines)) {
    fwrite(STDERR, "[SKIP] No new PHP source lines found\n");
    echo json_encode(['skipped' => true, 'reason' => 'no new PHP lines']);
    exit(0);
}

// ── Step 2: parse clover.xml for per-line hit counts ─────────────────────────

$xml = @simplexml_load_file($cloverFile);
if ($xml === false) {
    fwrite(STDERR, "[ERROR] Failed to parse clover.xml — skipping coverage check\n");
    echo json_encode(['skipped' => true, 'reason' => 'clover.xml parse error']);
    exit(0);  // don't block the PR on a tooling failure
}

// Build map: absolute_path => [ lineNum => hitCount ]
$cloverCoverage = [];
foreach ($xml->project->file as $fileNode) {
    $absPath = (string) $fileNode['name'];
    $cloverCoverage[$absPath] = [];
    foreach ($fileNode->line as $lineNode) {
        $cloverCoverage[$absPath][(int) $lineNode['num']] = (int) $lineNode['count'];
    }
}

function lookupLineCoverage(string $relPath, string $workspace, array $cloverCoverage): ?array
{
    $abs = $workspace . '/' . $relPath;
    return $cloverCoverage[$abs] ?? $cloverCoverage[$relPath] ?? null;
}

// ── Step 3: cross-reference new lines with clover ────────────────────────────

$totalExecutable = 0;
$totalCovered    = 0;
$uncoveredByFile = [];   // [ 'app/Foo.php' => [lineNum, ...] ]

foreach ($addedLines as $relPath => $lines) {
    $lineCov = lookupLineCoverage($relPath, $workspace, $cloverCoverage);

    if ($lineCov === null) {
        // File never loaded during any test run — all added lines are uncovered
        foreach ($lines as $lineNum) {
            $totalExecutable++;
            $uncoveredByFile[$relPath][] = $lineNum;
        }
        fwrite(STDERR, "[UNCOVERED] {$relPath}: not in clover (no test exercises this file)\n");
        continue;
    }

    foreach ($lines as $lineNum) {
        if (!array_key_exists($lineNum, $lineCov)) {
            continue;  // not executable: blank line, comment, closing brace, etc.
        }
        $totalExecutable++;
        if ($lineCov[$lineNum] > 0) {
            $totalCovered++;
        } else {
            $uncoveredByFile[$relPath][] = $lineNum;
        }
    }
}

if ($totalExecutable === 0) {
    fwrite(STDERR, "[SKIP] No new executable lines found\n");
    echo json_encode(['skipped' => true, 'reason' => 'no new executable lines']);
    exit(0);
}

$pct    = round($totalCovered / $totalExecutable * 100, 1);
$passed = $pct >= $threshold;

fwrite(STDERR, sprintf(
    "[RESULT] %d/%d new executable lines covered (%.1f%%) — threshold: %d%%\n",
    $totalCovered, $totalExecutable, $pct, $threshold
));

foreach ($uncoveredByFile as $file => $lines) {
    fwrite(STDERR, "  [UNCOVERED] {$file}: lines " . implode(', ', $lines) . "\n");
}

echo json_encode([
    'passed'          => $passed,
    'coverage'        => $pct,
    'threshold'       => $threshold,
    'covered'         => $totalCovered,
    'total'           => $totalExecutable,
    'uncovered_files' => $uncoveredByFile,
], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);

exit($passed ? 0 : 1);
